# Generated by Django 2.2.8 on 2020-12-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0002_auto_20201221_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
