# Generated by Django 2.2.8 on 2020-12-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0003_auto_20201221_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
