# Generated by Django 2.2.8 on 2020-12-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0004_auto_20201228_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='free_trial_posts',
            field=models.IntegerField(default=10, verbose_name='تعداد پست\u200cهای رایگان'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='free_trial_posts',
            field=models.IntegerField(default=10, verbose_name='تعداد پست\u200cهای رایگان'),
        ),
    ]
