# Generated by Django 2.2.8 on 2020-12-29 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0005_auto_20201229_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='free_trial_posts',
        ),
        migrations.RemoveField(
            model_name='historicalaccount',
            name='free_trial_posts',
        ),
    ]
