# Generated by Django 2.2.8 on 2021-02-16 03:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0006_auto_20201229_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر')),
                ('rate', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='امتیاز')),
                ('scored', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_scores', to=settings.AUTH_USER_MODEL, verbose_name='امتیاز گیرنده')),
                ('scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_scores', to=settings.AUTH_USER_MODEL, verbose_name='امتیاز دهنده')),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیازها',
            },
        ),
    ]
