# Generated by Django 2.2.8 on 2020-12-10 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='ad_posters/', verbose_name='تصویر')),
                ('title', models.CharField(max_length=30, verbose_name='نام کتاب')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('ad_type', models.CharField(db_index=True, default='sale', max_length=20, verbose_name='نوع درخواست')),
                ('price', models.IntegerField(default=20000, verbose_name='قیمت')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
        ),
    ]
