# Generated by Django 2.2.8 on 2020-12-10 04:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookad',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='bookad',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='زمان ساخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookad',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر'),
        ),
    ]
