# Generated by Django 2.2.8 on 2020-12-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_advertisement', '0002_auto_20201210_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookad',
            name='authorName',
            field=models.CharField(default='بی\u200cنام', max_length=30, verbose_name='نام نویسنده'),
        ),
    ]
